### ISSUE TITLE
在client端执行shell脚本报错失败

### ISSUE THREAD

**Issue by w675881684** [hequan2017/autoops#2]
可以在client端执行命令行，但是执行在client端执行shell脚本时报错，提示

主机:10.50.50.50
结果: 
 账号密码不对,或没有权限,请修改'l_50_50'

**Comment by hequan2017** [comment]
欢迎加群讨论  620176501  。     你添加的主机的时候 是选择的  root账号吗？

**Comment by w675881684** [comment]
是的root账号密码，刚才我在http://42.62.55.58:8003测试环境试了一下，公网的rhel6，也是存在同样问题，client端的command line能正常运行，但是shell脚本执行失败

**Comment by hequan2017** [comment]
好的。我这边再测试一下

**Comment by hequan2017** [comment]
方便提供一下 你的 shell脚本命令吗？

**Comment by w675881684** [comment]
就是比较简单的shell
#!/bin/bash
ls

**Comment by w675881684** [comment]
谢谢哈，就是比较简单的shell
#!/bin/bash
ls

**Comment by w675881684** [comment]
找到一个workaround方法
先对主机执行一次“硬件信息刷新”，然后就可以有权限执行shell了
