### ISSUE TITLE
命令执行好像有问题

### ISSUE THREAD

**Issue by Tim1995** [hequan2017/autoops#5]
我在执行命令行，输入whoami，显示出来了，然后在看的时候，机子的IP消失了，我不知道是bug，还是我就把机子搞跪了

**Comment by hequan2017** [comment]
用demo执行 正常，不太明白 你的这个问题。有截图吗

**Comment by Tim1995** [comment]
截图没弄，就是执行任务-->命令行  我执行了一个whoami命令，回显正常，然后再次刷新这个页面的时候，原有的主机IP消失了，目前不确定是bug，还是主机当时出现问题了

**Comment by hequan2017** [comment]
是用 admin 操作的吗？
